<?php
return array(
    "url" => array(
        "name"	=>	"自定义url",
        "type"	=>	0,
        "fname"	=>	"url地址",
        "field"	=>	"url",
    ),
    "index" => array(
        "name"	=>	"首页",
        "type"	=>	1,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "tuan_list" => array(
        "name"	=>	"团购列表",
        "type"	=>	11,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "good_list" => array(
        "name"	=>	"商品列表",
        "type"	=>	12,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "event_list" => array(
        "name"	=>	"活动列表",
        "type"	=>	14,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "youhui_list" => array(
        "name"	=>	"优惠券列表",
        "type"	=>	15,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "store_list" => array(
        "name"	=>	"门店列表",
        "type"	=>	26,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "shop_index" => array(
        "name"	=>	"商城首页",
        "type"	=>	102,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "tuan_index" => array(
        "name"	=>	"团购首页",
        "type"	=>	103,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "search" => array(
        "name"	=>	"搜索",
        "type"	=>	105,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "cart" => array(
        "name"	=>	"购物车",
        "type"	=>	106,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "user_center" => array(
        "name"	=>	"会员中心",
        "type"	=>	107,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "msg_center" => array(
        "name"	=>	"消息中心",
        "type"	=>	108,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "uc_account" => array(
        "name"	=>	"账户管理",
        "type"	=>	201,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "uc_score" => array(
        "name"	=>	"我的积分",
        "type"	=>	202,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "uc_youhui" => array(
        "name"	=>	"优惠券",
        "type"	=>	203,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "uc_share" => array(
        "name"	=>	"分享有礼",
        "type"	=>	204,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "uc_ecv" => array(
        "name"	=>	"红包",
        "type"	=>	206,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "uc_coupon" => array(
        "name"	=>	"消费券",
        "type"	=>	207,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "money_log" => array(
        "name"	=>	"资金明细",
        "type"	=>	301,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "uc_order_view" =>array(
        "name"	=>	"订单详情",
        "type"	=>	302,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "uc_fx_income"=>array(
        "name"	=>	"分销收益统计",
        "type"	=>	303,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "withdraw_log"=>array(
        "name"	=>	"提现明细",
        "type"	=>	304,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "common_order_list"=>array(
        "name"	=>	"我的订单--普通订单列表",
        "type"	=>	305,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "refund_order_list"=>array(
        "name"	=>	"我的订单--退单订单列表",
        "type"	=>	306,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "buy_order_list"=>array(
        "name"	=>	"我的订单--买单订单列表",
        "type"	=>	307,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "order_detail"=>array(
        "name"	=>	"订单详情",
        "type"	=>	308,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "pay_done"=>array(
        "name"	=>	"交易完成",
        "type"	=>	309,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "order_evaluate"=>array(
        "name"	=>	"订单评价",
        "type"	=>	310,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "choose_refund_goods"=>array(
        "name"	=>	"选择退款商品",
        "type"	=>	311,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "refund_apply"=>array(
        "name"	=>	"退款申请",
        "type"	=>	312,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "coupon"=>array(
        "name"	=>	" 会员中心--消费劵",
        "type"	=>	313,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "youhui_coupon"=>array(
        "name"	=>	"会员中心--优惠劵",
        "type"	=>	314,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "event_coupon"=>array(
        "name"	=>	"会员中心--活动劵",
        "type"	=>	315,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "delivery_address"=>array(
        "name"	=>	"配送地址",
        "type"	=>	316,
        "fname"	=>	"",
        "field"	=>	"",
    ),
    "my_collection"=>array(
        "name"	=>	"我的收藏",
        "type"	=>	317,
        "fname"	=>	"",
        "field"	=>	"",
    ),
);
